/* data.jsx — Mock data + helpers for Forumo prototype */

const SELLERS = {
  s1: {
    id: "s1",
    name: "Adaeze Okafor",
    shop: "Adaeze Vintage",
    location: "Lagos, NG",
    rating: 4.9,
    reviews: 312,
    responseTime: "Replies in ~1h",
    verified: true,
    joined: "Jan 2023",
  },
  s2: {
    id: "s2",
    name: "Kojo Mensah",
    shop: "Accra Hi-Fi",
    location: "Accra, GH",
    rating: 4.8,
    reviews: 184,
    responseTime: "Replies same day",
    verified: true,
    joined: "Mar 2023",
  },
  s3: {
    id: "s3",
    name: "Sade Balogun",
    shop: "Ile Atelier",
    location: "Ibadan, NG",
    rating: 5.0,
    reviews: 78,
    responseTime: "Replies in ~2h",
    verified: true,
    joined: "Jul 2024",
  },
  s4: {
    id: "s4",
    name: "Lerato Dube",
    shop: "JHB Curated",
    location: "Johannesburg, ZA",
    rating: 4.7,
    reviews: 421,
    responseTime: "Replies in ~3h",
    verified: true,
    joined: "Aug 2022",
  },
};

const LISTINGS = [
  {
    id: "l1",
    sellerId: "s1",
    title: "Mid-century walnut sideboard, restored",
    price: 18500000,
    currency: "NGN",
    condition: "Excellent — fully restored",
    category: "Home & Living",
    placeholder: "sideboard",
    stock: 1,
    watching: 24,
    posted: "2 days ago",
  },
  {
    id: "l2",
    sellerId: "s2",
    title: "Technics SL-1200 MK2 turntable, serviced",
    price: 8200000,
    currency: "NGN",
    condition: "Good — minor cosmetic wear",
    category: "Electronics",
    placeholder: "turntable",
    stock: 1,
    watching: 41,
    posted: "5 days ago",
  },
  {
    id: "l3",
    sellerId: "s3",
    title: "Handwoven aso-oke throw, indigo",
    price: 4500000,
    currency: "NGN",
    condition: "New from maker",
    category: "Home & Living",
    placeholder: "textile",
    stock: 6,
    watching: 12,
    posted: "1 day ago",
  },
  {
    id: "l4",
    sellerId: "s1",
    title: "Brass kerosene lantern, 1960s",
    price: 1850000,
    currency: "NGN",
    condition: "Good — patina intact",
    category: "Home & Living",
    placeholder: "lantern",
    stock: 1,
    watching: 8,
    posted: "3 days ago",
  },
  {
    id: "l5",
    sellerId: "s4",
    title: "Olympus OM-1 with 50mm f/1.8",
    price: 6750000,
    currency: "NGN",
    condition: "Very good — recent CLA",
    category: "Electronics",
    placeholder: "camera",
    stock: 1,
    watching: 36,
    posted: "6 days ago",
  },
  {
    id: "l6",
    sellerId: "s4",
    title: "Yamaha NS-10M studio monitors (pair)",
    price: 9800000,
    currency: "NGN",
    condition: "Good — original drivers",
    category: "Electronics",
    placeholder: "speakers",
    stock: 1,
    watching: 19,
    posted: "Today",
  },
  {
    id: "l7",
    sellerId: "s3",
    title: "Stoneware coffee set for four",
    price: 3200000,
    currency: "NGN",
    condition: "New from maker",
    category: "Home & Living",
    placeholder: "ceramics",
    stock: 3,
    watching: 5,
    posted: "4 days ago",
  },
  {
    id: "l8",
    sellerId: "s2",
    title: "Sennheiser HD 600 headphones",
    price: 1950000,
    currency: "NGN",
    condition: "Excellent — earpads replaced",
    category: "Electronics",
    placeholder: "headphones",
    stock: 2,
    watching: 15,
    posted: "2 days ago",
  },
];

const CATEGORIES = [
  "All",
  "Home & Living",
  "Electronics",
  "Fashion",
  "Art & Craft",
  "Books",
  "Auto Parts",
];

const REVIEWS = [
  {
    name: "Tunde A.",
    rating: 5,
    when: "3 weeks ago",
    text: "Exactly as described. Packaging was extreme — wrapped twice. Escrow released same-day.",
  },
  {
    name: "Mariam B.",
    rating: 5,
    when: "Last month",
    text: "Adaeze was patient with my many questions and even sent extra photos. Beautiful piece.",
  },
  {
    name: "Chinedu O.",
    rating: 4,
    when: "2 months ago",
    text: "Minor scuff on the back panel not shown in listing, but seller offered partial refund quickly.",
  },
];

window.FORUMO_DATA = { SELLERS, LISTINGS, CATEGORIES, REVIEWS };
