export const queryKeys = {
  listings: (params: Record<string, unknown>) => ['listings', params] as const,
  listing: (id: string) => ['listing', id] as const,
  listingReviews: (listingId: string) => ['listing', listingId, 'reviews'] as const,
  sellerReviewRollup: (sellerId: string) => ['seller', sellerId, 'reviews'] as const,
  orders: ['orders'] as const,
  order: (id: string) => ['orders', id] as const,
  threads: (userId?: string | null, page = 1) => ['threads', userId ?? 'self', page] as const,
  thread: (id: string) => ['thread', id] as const,
  notifications: ['notifications'] as const,
  notificationUnreadCount: ['notifications', 'unread-count'] as const,
  profile: ['profile'] as const,
  offers: ['offers'] as const,
  wishlist: ['wishlist'] as const,
  wishlistCheck: (listingId: string) => ['wishlist', 'check', listingId] as const,
  categories: ['categories'] as const,
  tags: ['tags'] as const,
  myStorefront: ['storefront', 'me'] as const,
  myCollections: ['storefront', 'me', 'collections'] as const,
  myListings: ['listings', 'mine'] as const,
  auctions: (params: Record<string, unknown>) => ['auctions', params] as const,
  escrowDetails: (orderId: string) => ['escrow', orderId] as const,
  payoutBalance: ['payouts', 'balance'] as const,
  payouts: (page: number) => ['payouts', 'list', page] as const,
  payoutOnboard: ['payouts', 'onboard'] as const,
};
