export const queryKeys = {
  listings: (params: Record<string, unknown>) => ['listings', params] as const,
  listing: (id: string) => ['listing', id] as const,
  listingReviews: (listingId: string) => ['listing', listingId, 'reviews'] as const,
  sellerReviewRollup: (sellerId: string) => ['seller', sellerId, 'reviews'] as const,
  orders: ['orders'] as const,
  order: (id: string) => ['orders', id] as const,
  deliveredOrdersForListing: (listingId: string) => ['orders', 'delivered', listingId] as const,
  threads: (userId?: string | null, page = 1) => ['threads', userId ?? 'self', page] as const,
  thread: (id: string) => ['thread', id] as const,
  notifications: ['notifications'] as const,
  notificationUnreadCount: ['notifications', 'unread-count'] as const,
  profile: ['profile'] as const,
  offers: ['offers'] as const,
  wishlist: ['wishlist'] as const,
  wishlistCheck: (listingId: string) => ['wishlist', 'check', listingId] as const,
  categories: ['categories'] as const,
  tags: ['tags'] as const,
  myStorefront: ['storefront', 'me'] as const,
  myCollections: ['storefront', 'me', 'collections'] as const,
  myListings: ['listings', 'mine'] as const,
  auctions: (params: Record<string, unknown>) => ['auctions', params] as const,
  escrowDetails: (orderId: string) => ['escrow', orderId] as const,
  payoutBalance: ['payouts', 'balance'] as const,
  payouts: (page: number) => ['payouts', 'list', page] as const,
  payoutOnboard: ['payouts', 'onboard'] as const,
  feeSchedules: ['admin', 'fee-schedules'] as const,
  feePreview: (listingId: string, subtotalCents: number) => ['fees', 'preview', listingId, subtotalCents] as const,
  returns: ['returns'] as const,
  return: (id: string) => ['returns', id] as const,
  sellerAnalyticsOverview: (period: string) => ['seller', 'analytics', 'overview', period] as const,
  sellerAnalyticsRevenue: (period: string, groupBy: string) => ['seller', 'analytics', 'revenue', period, groupBy] as const,
  sellerAnalyticsTopListings: ['seller', 'analytics', 'top-listings'] as const,
  sellerAnalyticsReviews: ['seller', 'analytics', 'reviews-summary'] as const,
  listingAuction: (listingId: string) => ['auctions', 'listing', listingId] as const,
};
